#pragma once

enum TEXTURE_IDS {
	WATER_POSITIONS = 1,
	WATER_POSITIONS_PREV = 2,
	WATER_NORMALS = 3,
	FLOOR_TILT = 4,
	SPHERE = 5,
	CAUSTICS = 6
};

enum WALL_NUMBERS {
	FLOOR = 0,
	LEFT_WALL = 1,
	RIGHT_WALL = 2,
	FRONT_WALL = 3,
	BACK_WALL = 4
};
